spring:
  application:
    name: praktikum_module_2

kafka:
  bootstrap-servers: localhost:9095, localhost:9096
  acks: all
  retries: 3
  replicas: 2
  topic-messages: messages
  topic-deprecated-words: deprecated-words
  topic-filtered-messages: filtered-messages
  topic-blocked-users: blocked-users